/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SidecarInsightsRouteImport } from './routes/sidecar/insights'
import { Route as NotesNoteIdRouteImport } from './routes/notes/$noteId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SidecarInsightsRoute = SidecarInsightsRouteImport.update({
  id: '/sidecar/insights',
  path: '/sidecar/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesNoteIdRoute = NotesNoteIdRouteImport.update({
  id: '/notes/$noteId',
  path: '/notes/$noteId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/notes/$noteId': typeof NotesNoteIdRoute
  '/sidecar/insights': typeof SidecarInsightsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/notes/$noteId': typeof NotesNoteIdRoute
  '/sidecar/insights': typeof SidecarInsightsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/notes/$noteId': typeof NotesNoteIdRoute
  '/sidecar/insights': typeof SidecarInsightsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/notes/$noteId' | '/sidecar/insights'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/notes/$noteId' | '/sidecar/insights'
  id: '__root__' | '/' | '/notes/$noteId' | '/sidecar/insights'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NotesNoteIdRoute: typeof NotesNoteIdRoute
  SidecarInsightsRoute: typeof SidecarInsightsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sidecar/insights': {
      id: '/sidecar/insights'
      path: '/sidecar/insights'
      fullPath: '/sidecar/insights'
      preLoaderRoute: typeof SidecarInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/$noteId': {
      id: '/notes/$noteId'
      path: '/notes/$noteId'
      fullPath: '/notes/$noteId'
      preLoaderRoute: typeof NotesNoteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NotesNoteIdRoute: NotesNoteIdRoute,
  SidecarInsightsRoute: SidecarInsightsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
